-- MySQL Script generated by MySQL Workbench
-- 03/05/17 19:31:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbteste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbteste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbteste` DEFAULT CHARACTER SET utf8 ;
USE `dbteste` ;

-- -----------------------------------------------------
-- Table `dbteste`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(2) NOT NULL COMMENT 'AT=ATIVO\nIN=INATIVO\n',
  `tipo` VARCHAR(1) NOT NULL COMMENT 'F=FISICA\nJ=JURIDICA\n',
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(30) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `dt_atualizacao` DATETIME NULL DEFAULT NULL,
  `dt_cadastro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`juridica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `cnpj` VARCHAR(100) NOT NULL,
  `razao_social` VARCHAR(200) NOT NULL,
  `nome_fantasia` VARCHAR(200) NOT NULL,
  `inscricao_estadual` VARCHAR(100) NULL DEFAULT NULL,
  `ccm` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  INDEX `fk_juridica_pessoa2_idx` (`pessoa_id` ASC),
  UNIQUE INDEX `pessoa_id_UNIQUE` (`pessoa_id` ASC),
  CONSTRAINT `fk_juridica_pessoa2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `dbteste`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`fisica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `rg` VARCHAR(20) NULL DEFAULT NULL,
  `dt_nascimento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NULL DEFAULT NULL COMMENT 'SEXO:\nH=HOMEM\nM=MULHER\n',
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_fisica_pessoa2_idx` (`pessoa_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pessoa_id_UNIQUE` (`pessoa_id` ASC),
  CONSTRAINT `fk_fisica_pessoa2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `dbteste`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`unidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `codbar` VARCHAR(255) NULL DEFAULT NULL,
  `categoria_id` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(1000) NULL DEFAULT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `unidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `codbar_UNIQUE` (`codbar` ASC),
  INDEX `fk_produto_unidade1_idx` (`unidade_id` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dbteste`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_unidade1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `dbteste`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_funcionario_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_funcionario_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `dbteste`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`entrada_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`entrada_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto_id` INT NOT NULL,
  `fornecedor_id` INT NOT NULL,
  `quantidade` DECIMAL(10,0) NOT NULL,
  `lote` VARCHAR(45) NULL DEFAULT NULL,
  `dt_compra` DATE NOT NULL,
  `dt_validade` DATE NULL DEFAULT NULL,
  `valor_unitario` DECIMAL(7,2) NULL DEFAULT NULL,
  `valor_total` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entrada_produto_produto1_idx` (`produto_id` ASC),
  INDEX `fk_entrada_produto_pessoa1_idx` (`fornecedor_id` ASC),
  CONSTRAINT `fk_entrada_produto_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `dbteste`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_produto_pessoa1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `dbteste`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `desconto` VARCHAR(45) NULL DEFAULT NULL,
  `total` DECIMAL(7,2) NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `data`),
  INDEX `fk_venda_pessoa1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_venda_pessoa1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dbteste`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`itens_venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venda_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` VARCHAR(45) NULL DEFAULT NULL,
  `valor_unitario` DECIMAL(7,2) NULL DEFAULT NULL,
  INDEX `fk_itens_venda_venda1_idx` (`venda_id` ASC),
  INDEX `fk_itens_venda_produto1_idx` (`produto_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_itens_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `dbteste`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_venda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `dbteste`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`modulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `pai` INT(11) NULL DEFAULT NULL,
  `statusID` TINYTEXT NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modulo_modulo1_idx` (`pai` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbteste`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`acesso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modulo_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  `nivel_acesso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acesso_funcionario1_idx` (`funcionario_id` ASC),
  INDEX `fk_acesso_modulo1` (`modulo_id` ASC),
  CONSTRAINT `fk_acesso_modulo1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `dbteste`.`modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `dbteste`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
